#!/usr/bin/env python3
"""
Generate a markdown weekly delay summary for all tracked trains and write it
to reports/weekly-<iso_week>.md. Meant to be run via cron once a week (see
crontab.example), or manually:

    python scripts/weekly_report.py
"""
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app import aggregate, config, db

REPORTS_DIR = config.PROJECT_ROOT / "reports"


def build_report() -> str:
    weekly = aggregate.weekly_stats(weeks=1)
    trains = {t["train_number"]: t for t in aggregate.train_summary()}

    lines = [f"# Weekly delay report — {date.today().isoformat()}", ""]

    if not weekly:
        lines.append("No completed journeys observed this week yet.")
        return "\n".join(lines)

    lines.append("| Train | Name | Runs | Avg delay | Median | Max | On-time % |")
    lines.append("|---|---|---|---|---|---|---|")
    for row in weekly:
        name = trains.get(row["train_number"], {}).get("name") or ""
        lines.append(
            f"| {row['train_number']} | {name} | {row['runs_observed']} | "
            f"{row['avg_delay_minutes']}m | {row['median_delay_minutes']}m | "
            f"{row['max_delay_minutes']}m | {row['on_time_pct']}% |"
        )

    lines.append("")
    lines.append("_On-time defined as delay ≤ 10 minutes. Generated by scripts/weekly_report.py._")
    return "\n".join(lines)


def main() -> int:
    db.init_db()
    report = build_report()
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    iso_year, iso_week, _ = date.today().isocalendar()
    out_path = REPORTS_DIR / f"weekly-{iso_year}-W{iso_week:02d}.md"
    out_path.write_text(report)
    print(report)
    print(f"\nWritten to {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
